### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [SpintroniK/exadrums-data#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by SpintroniK** [comment]
This repo is just a placeholder for some configuration files, I didn't really feel the need to add a license...
But if the default is copyright, I added a license file.
I'm in favor of the MIT license.
